### ISSUE TITLE
Route53: conflicting RRSet of type CNAME with the same DNS name already exists in zone

### ISSUE THREAD

**Issue by Saba-Shavidze** [RJPearson94/terraform-aws-open-next#24]
``` 
creating Route 53 Record: InvalidChangeBatch: [RRSet of type A with DNS name www.dev.xxx.ge. is not permitted because a conflicting RRSet of type CNAME with the same DNS name already exists in zone dev.xxx.ge.]
│ 
│   with module.deploy.module.public_resources[0].aws_route53_record.route53_a_record["www_dev.xxx.ge-false"],
│   on terraform-aws-open-next/modules/tf-aws-open-next-public-resources/main.tf line 1346, in resource "aws_route53_record" "route53_a_record":
│ 1346: resource "aws_route53_record" "route53_a_record" {
```

## Domain configuration
```ts
domain_config = {
    viewer_certificate = {
      acm_certificate_arn = local.acm_certificate_arn
    }
    include_www                    = true
    route53_record_allow_overwrite = true
    hosted_zones = flatten([
      for name in keys(local.route53_zone_zone_id) : { name = name }
    ])
  }
```

**Comment by RJPearson94** [comment]
Hi @Saba-Shavidze,

Apologises for the slow response 

Looking at the error, is the dns record you are trying to overwrite a CNAME?


Reading this post https://repost.aws/knowledge-center/troubleshoot-route53-resource-record it explains that you will get an error when trying to change a CNAME to an A record. Detail below

An error occurred (InvalidChangeBatch) when calling the ChangeResourceRecordSets operation: [RRSet of type A with DNS name b.domain.com. is not permitted because a conflicting RRSet of type CNAME with the same DNS name already exists in zone b.domain.com.]
If you're updating a CNAME record to any other record using "UPSERT", or you're trying to change an existing record to a CNAME record, you receive this error.

The UPSERT is successful only if you originally had a CNAME record and UPSERT to another CNAME record.

**Comment by RJPearson94** [comment]
If your record is already a CNAME you may need to use another domain or remove the CNAME record and then create the new A and AAAA records

**Comment by Saba-Shavidze** [comment]
Aaah I see, Sorry that was my issue, thanks again for take your time and answer

**Comment by RJPearson94** [comment]
No problem, glad I could help
