### ISSUE TITLE
server actions - CloudFront behaviour issue

### ISSUE THREAD

**Issue by copyPasteNinja** [RJPearson94/terraform-aws-open-next#3]
## Technical Details

- OS: [e.g. MacOS]
- Terraform Version: "~> 1.5"
- AWS Provider Version "~> 4.0"
- Module Version = "1.2.0"

## Describe the bug

I've deployed my NextJs app using the module and everything works as expected except when I use a function on my application. I have a function in NextJs that sends an email by making an api call to "SendGrid". This function works perfectly when application running locally but when deployed using this module I can't get through CloudFront 403 error. 

## Steps to Reproduce

Steps to reproduce the behaviour:

1. I did not use terragrunt just used terraform to execute my code
2. This is basically what my module looks like: 
```
module "open_next" {
  source  = "registry.terraform.io/RJPearson94/open-next/aws"
  version = "1.2.0"
  prefix  = "${var.env}-${var.project}"
  providers = {
    aws                 = aws
    aws.iam             = aws.iam
    aws.dns             = aws.dns
    aws.server_function = aws.server_function
  }
  domain = {
    create              = true
    hosted_zone_name    = local.domain_name
    name                = local.domain_name
    alternate_names     = [local.domain_name, "www.${local.domain_name}"]
    acm_certificate_arn = aws_acm_certificate.ssl_certificate.arn
  }
  open_next = {
    root_folder_path = "../../.open-next"
  }
}
```

## Expected behaviour

I would expect my post request to trigger lambda and do api call to sendgrid and send the email(s).

## Logs

Here is what I get from CloudFront upon request (in inspect > network) 
```
403 ERROR
The request could not be satisfied.
This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
```

## Additional context

I tried to change bunch of things, I'm not sure what I am doing wrong or what I can do to resolve this. 
Please help 🙏

**Comment by copyPasteNinja** [comment]
I appreciate the quick response! Unfortunately the project is not public (sorry). 

My next version: `next: "13.4.19"`

I'm actually using the experimental feature (Server Actions): 
```const nextConfig = {
  images: {
    domains: ["tailwindui.com"],
  },
  experimental: {
    serverActions: true,
  },
};
```

Specific use-case: 
```
"use server";

export default async function ContactUsEmail(data: {
  firstName: string;
  lastName: string;
  company: string;
  phone: string;
  email: string;
  message: string;
}) {
  const sgMail = require("@sendgrid/mail");
  sgMail.setApiKey(process.env.SENDGRID_TOKEN);

  const msg = {
    to: "test@exmaple.com", // Change to your recipient
    from: "info@exmaple.com", // Change to your verified sender
    subject: "Client Trying to Reach you",
    html: `<h3>${data.firstName} ${data.lastName} reaching out to you</h3>
      <br>
      <p><b>Name: </b> ${data.firstName} ${data.lastName} </p>
      <p><b>Email: </b> ${data.email}</p>
      <p><b>Phone Number: </b> ${data.phone} </p>
      <p><b>Company: </b> ${data.company} </p>
      <p><b>Message: </b> ${data.message} </p>`,
  };

  try {
    await sgMail.send(msg);

    console.log("Email sent");
  } catch (error) {
    console.error(error);
  }
}
```

**Comment by RJPearson94** [comment]
Hi @copyPasteNinja,

I have replicated this issue using both server actions and api routes. The issue is caused by the behaviours that are recommended for the opennext configuration. 

The behaviours that are set by default are as follows
api/*
_next/data/*
_next/image*
_next/*
Default (*)

The module/ configuration is expecting you to make POST requests to the /api/* endpoint, whereas the server action is making the post request on the same path as the page is loaded i.e. if you have a contact us form on the following url https://<cloudfront_domain>/contact-us whereas the configuration would expect the POST request to be made to https://<cloudfront_domain>/api/contact-us 

I will need to do some research/ ask on the open next repo on how they planned to support this however, this will not be a quick fix. 
If possible, I would recommend using the API route instead and create a `route.(ts|js)` file in the  `app/api/contact-us` folder. You can then call this route from your component, and everything should work as expected.

I hope this helps.
I will keep this issue open whilst I investigate how the module can support server actions

Kind Regards
Rob

**Comment by copyPasteNinja** [comment]
Thank you very much, I will use routes until the feature in production then. Again, thank you very much.

**Comment by copyPasteNinja** [comment]
Thank you very much, I will use routes until the feature in production then. Again, thank you very much.

**Comment by RJPearson94** [comment]
In Open Next 2.x the behaviours were modified around the default behaviour. 
In v2 of the module support for open next 1.x is removed which resolves this issue
